/* Generated by Yosys 0.8+498 (git sha1 1bdc7e9d, gcc 7.4.0-1ubuntu1~18.04 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "attrib04_net_var.v:1" *)
module bar(clk, rst, inp, out);
  (* src = "attrib04_net_var.v:13" *)
  reg [7:0] _0_;
  (* src = "attrib04_net_var.v:18" *)
  reg _1_;
  (* src = "attrib04_net_var.v:14" *)
  wire [31:0] _2_;
  (* src = "attrib04_net_var.v:16" *)
  wire _3_;
  (* src = "attrib04_net_var.v:2" *)
  input clk;
  (* src = "attrib04_net_var.v:8" *)
  (* this_is_a_prescaler = 32'd1 *)
  reg [7:0] counter;
  (* src = "attrib04_net_var.v:4" *)
  input inp;
  (* src = "attrib04_net_var.v:5" *)
  output out;
  reg out;
  (* src = "attrib04_net_var.v:11" *)
  (* temp_wire = 32'd1 *)
  wire out_val;
  (* src = "attrib04_net_var.v:3" *)
  input rst;
  assign _2_ = counter + (* src = "attrib04_net_var.v:14" *) 32'd1;
  assign _3_ = inp ^ (* src = "attrib04_net_var.v:16" *) counter[4];
  always @* begin
    _0_ = _2_[7:0];
  end
  always @(posedge clk) begin
      counter <= _0_;
  end
  always @* begin
    _1_ = out;
    casez (rst)
      1'h1:
          _1_ = 1'h0;
      default:
          _1_ = out_val;
    endcase
  end
  always @(posedge clk) begin
      out <= _1_;
  end
  assign out_val = _3_;
endmodule

(* cells_not_processed =  1  *)
(* src = "attrib04_net_var.v:24" *)
module foo(clk, rst, inp, out);
  (* src = "attrib04_net_var.v:25" *)
  input clk;
  (* src = "attrib04_net_var.v:27" *)
  input inp;
  (* src = "attrib04_net_var.v:28" *)
  output out;
  (* src = "attrib04_net_var.v:26" *)
  input rst;
  (* module_not_derived = 32'd1 *)
  (* src = "attrib04_net_var.v:30" *)
  bar bar_instance (
    clk,
    rst,
    inp,
    out
  );
endmodule
