/* Generated by Yosys 0.8+498 (git sha1 abef145f, gcc 7.4.0-1ubuntu1~18.04 -fPIC -Os) */

(* dynports =  1  *)
(* cells_not_processed =  1  *)
(* src = "attrib03_parameter.v:1" *)
module bar(clk, rst, inp, out);
  (* bus_width = 32'd1 *)
  parameter \WIDTH = 32'd2;
  (* src = "attrib03_parameter.v:14" *)
  reg [1:0] _0_;
  (* src = "attrib03_parameter.v:16" *)
  wire [31:0] _1_;
  (* src = "attrib03_parameter.v:9" *)
  input clk;
  (* src = "attrib03_parameter.v:11" *)
  input [1:0] inp;
  (* src = "attrib03_parameter.v:12" *)
  output [1:0] out;
  reg [1:0] out;
  (* src = "attrib03_parameter.v:10" *)
  input rst;
  assign _1_ = inp + (* src = "attrib03_parameter.v:16" *) 32'd5;
  always @* begin
    _0_ = out;
    casez (rst)
      1'h1:
          _0_ = 2'h0;
      default:
          _0_ = _1_[1:0];
    endcase
  end
  always @(posedge clk) begin
      out <= _0_;
  end
endmodule

(* cells_not_processed =  1  *)
(* src = "attrib03_parameter.v:20" *)
module foo(clk, rst, inp, out);
  (* src = "attrib03_parameter.v:21" *)
  input clk;
  (* src = "attrib03_parameter.v:23" *)
  input [7:0] inp;
  (* src = "attrib03_parameter.v:24" *)
  output [7:0] out;
  (* src = "attrib03_parameter.v:22" *)
  input rst;
  (* module_not_derived = 32'd1 *)
  (* src = "attrib03_parameter.v:26" *)
  bar #(
    .WIDTH(32'sd8)
  ) bar_instance (
    clk,
    rst,
    inp,
    out
  );
endmodule
