/* Generated by Yosys 0.8+498 (git sha1 1bdc7e9d, gcc 7.4.0-1ubuntu1~18.04 -fPIC -Os) */

(* cells_not_processed =  1  *)
(* src = "attrib05_port_conn.v:1" *)
module bar(clk, rst, inp, out);
  (* src = "attrib05_port_conn.v:7" *)
  reg _0_;
  (* src = "attrib05_port_conn.v:9" *)
  wire _1_;
  (* src = "attrib05_port_conn.v:2" *)
  input clk;
  (* src = "attrib05_port_conn.v:4" *)
  input inp;
  (* src = "attrib05_port_conn.v:5" *)
  output out;
  reg out;
  (* src = "attrib05_port_conn.v:3" *)
  input rst;
  assign _1_ = ~ (* src = "attrib05_port_conn.v:9" *) inp;
  always @* begin
    _0_ = out;
    casez (rst)
      1'h1:
          _0_ = 1'h0;
      default:
          _0_ = _1_;
    endcase
  end
  always @(posedge clk) begin
      out <= _0_;
  end
endmodule

(* cells_not_processed =  1  *)
(* src = "attrib05_port_conn.v:13" *)
module foo(clk, rst, inp, out);
  (* src = "attrib05_port_conn.v:14" *)
  input clk;
  (* src = "attrib05_port_conn.v:16" *)
  input inp;
  (* src = "attrib05_port_conn.v:17" *)
  output out;
  (* src = "attrib05_port_conn.v:15" *)
  input rst;
  (* module_not_derived = 32'd1 *)
  (* src = "attrib05_port_conn.v:19" *)
  bar bar_instance (
    (* clock_connected = 32'd1 *) clk,
    rst,
    (* this_is_the_input = 32'd1 *) inp,
    out
  );
endmodule
